name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup pnpm
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      uses: pnpm/action-setup@v4.0.0
      with:
        # If specified, run `pnpm install`
        run_install: true
        version: latest

    - name: Build
      run: |
        pnpm build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        # Path of the directory containing the static assets.
        path: dist/ # default is _site/
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
